values:
    scalar_value: 42

services:
    sensor_types:
        class: SensorTypeRepository
        module: nanobrew.core.domain.sensor_type_repository

    sensors:
        class: SqliteSensorRepository
        module: nanobrew.core.infrastructure.sqlite.sensor_repository
        dependencies:
            - sensor_types