values:
    database_name: "nanobrew.db"

services:
    sensor_types:
        class: SensorTypeRepository
        module: nanobrew.core.domain.sensor_type_repository

    sensors:
        class: SqliteSensorRepository
        module: nanobrew.core.infrastructure.sqlite.sensor_repository
        dependencies:
            - sqlite_connection
            - sensor_types

    sqlite_connection:
        class: Connection
        module: nanobrew.core.infrastructure.sqlite.connection
        dependencies:
            - value:database_name