values:
    database_name: "nanobrew.db"

services:
    sensor_types:
        class: SensorTypeRepository
        module: nanobrew.core.domain.sensor_type_repository

    sensors:
        class: SensorRepository
        module: nanobrew.core.domain.sensor_repository
        dependencies:
            - sensors_sqlite

    event_listener:
        class: EventListener
        module: nanobrew.core.application.event_listener
        dependencies:
            - event_bus

    event_bus:
        class: EventBus
        module: nanobrew.core.application.event_bus

    sensors_sqlite:
        class: SqliteSensorDataMapper
        module: nanobrew.core.infrastructure.sqlite.sensor_data_mapper
        dependencies:
            - sqlite_connection
            - sensor_types

    sqlite_connection:
        class: Connection
        module: nanobrew.core.infrastructure.sqlite.connection
        dependencies:
            - value:database_name